name: "My name is Dario Berzano"
description: "My personal page"

url: "dberzano.github.io"

permalink: /archive/:year/:month/:day/:title
paginate: 3
paginate_path: /archive/page:num

#markdown: rdiscount
markdown: redcarpet

redcarpet:
  extensions: [ "tables" ]

pygments: true

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: tweet
      createtoc: false
      parnumbers: false
