name: "My name is Dario Berzano"
description: "My personal page"

url: "dberzano.github.io"

paginate: 10

#markdown: rdiscount
markdown: redcarpet

redcarpet:
  extensions: [ "tables" ]

permalink: pretty
pygments: true
