name: "My name is Dario Berzano"
description: "My personal page"

url: "dberzano.github.io"

#permalink: /:year/:month/:day/:title
permalink: pretty
paginate: 3
paginate_path: /page:num

markdown: redcarpet

redcarpet:
  extensions: [ "tables" ]

highlighter: pygments

defaults:
  -
    scope:
      path: "" # empty string for all files
      type: post
    values:
      layout: tweet
      createtoc: false
      parnumbers: false
