name: "My name is Dario Berzano"
description: "My personal page"

url: "dberzano.github.io"

permalink: /archive/:year/:month/:day/:title
paginate: 3
paginate_path: /archive/page:num

#markdown: rdiscount
markdown: redcarpet

redcarpet:
  extensions: [ "tables" ]

pygments: true
